export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
};

export const verifyEmailConstants = {
  VERIFYEMAIL_REQUEST: 'VERIFYEMAIL_REQUEST',
  VERIFYEMAIL_FAILURE: 'VERIFYEMAIL_FAILURE',
  VERIFYEMAIL_SUCCESS: 'VERIFYEMAIL_SUCCESS',
  // VERIFYEMAIL_REQUEST: 'VERIFYEMAIL_REQUEST',
};


