export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
};

export const verifyEmailConstants = {
  VERIFYEMAIL_REQUEST: 'VERIFYEMAIL_REQUEST',
  VERIFYEMAIL_FAILURE: 'VERIFYEMAIL_FAILURE',
  VERIFYEMAIL_SUCCESS: 'VERIFYEMAIL_SUCCESS',
  // VERIFYEMAIL_REQUEST: 'VERIFYEMAIL_REQUEST',
};

export const customersConstants = {
  START_LOADING: 'LOAD_CUSTOMERS',
  ALLCUSTOMERS_FAILURE: 'IS_CUSTOMER_ERROR',
  ALLCUSTOMERS_SUCCESS: 'IS_CUSTOMER_SUCCESS',
  HAS_NEXTPAGE: 'HAS_NEXTPAGE',
  HAS_NEXTPAGE_FAILED: 'HAS_NEXTPAGE_FAILED',
};

export const OrderConstants = {
  START_LOADING: 'START_LOADING_ORDER',
  IS_ERROR: 'IS_ORDER_ERROR',
  IS_SUCCESS: 'IS_ORDER_SUCCESS',
  // ORDER_DELETE: 'ORDER_DELETE',
};

export const NotificationConstants = {
  START_LOADING: 'START_LOADING_NOTIFICATION',
  IS_ERROR: 'IS_NOTIFICATION_ERROR',
  IS_SUCCESS: 'IS_NOTIFICATION_SUCCESS',
};

export const VendorConstants = {
  START_LOADING: 'START_LOADING_VENDOR',
  IS_ERROR: 'IS_VENDOR_ERROR',
  IS_SUCCESS: 'IS_VENDOR_SUCCESS',
  ALLVENDORS_DELETE: 'VENDORS_DELETE',
};

export const ProductsConstants = {
  PRODUCTS_REQUEST: 'PRODUCTS_REQUEST',
  PRODUCTS_FAILURE: 'PRODUCTS_FAILURE',
  PRODUCTS_SUCCESS: 'PRODUCTS_SUCCESS',
  // PRODUCTS_FAILURE: "PRODUCTS_FAILURE",
};
